name: CI/CD
on: [push]
jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install
          entrypoint: ./
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: lint
          entrypoint: ./
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: build
          entrypoint: ./
  deploy:
    name: CD
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy
          entrypoint: ./
        env:
          FIREBASE_TOKEN: 1//0988KyW6r8JiKCgYIARAAGAkSNwF-L9IrifoUJyaSw1Qwaz2cNDGBg2uIQevJY6nEzmmvJkzh6RsarF6Q06PCdlucgI2Q9_UdnS4
